### ISSUE TITLE
matplotlib tight_layout not applied

### ISSUE THREAD

**Issue by sateeshperi** [dmnfarrell/smallrnaseq#3]
```
lib/python3.6/site-packages/matplotlib/tight_layout.py:181: UserWarning: Tight layout not applied. The bottom and top margins cannot be made large enough to accommodate all axes decorations. 
  warnings.warn('Tight layout not applied. '
```
This seems to be the reason for figure legend to overlap with the plot  
![libraries_mapped](https://user-images.githubusercontent.com/33637490/52075273-bbc69880-2540-11e9-9d01-ed7724270b5e.png)

Any suggestions on how to fix this?

**Comment by dmnfarrell** [comment]
I've made some changes to the plots that should improve this. It's not always easy to make labels fit if they are too large.
