### ISSUE TITLE
smallrnaseq output file data  

### ISSUE THREAD

**Issue by llusayl** [dmnfarrell/smallrnaseq#7]
I am trying this fabulous package for identification and quantitation of small ncRNAs.  In the output file, for each sample, there are two columns on counts, one is s0, and another s0.norm. I have two questions to ask for help. First, which column should I use for downstream DESeq2 (I assume should be s0 (raw counts), is it correct?)? Second, how is the column of s0.norm calculated based on the column s0? Thanks in advance, and stay well.

**Comment by dmnfarrell** [comment]
You should always use the raw data, s0, for differential expression analysis. The norm columns are there mainly for plotting purposes. They are just calculated by dividing by the total counts in all the genes for that sample. The package will optionally use edgeR to do the DE analysis if you give it the right groups and labels. https://smallrnaseq.readthedocs.io/en/latest/cli.html#differential-expression

**Comment by llusayl** [comment]
Thank you very much for confirmation.  Have a nice one, and stay well.
