### ISSUE TITLE
what label corresponds to what sample

### ISSUE THREAD

**Issue by Adnanhashim** [dmnfarrell/smallrnaseq#8]
Hi, 
Thanks for a wonderful tool for sncRNAs profiling. I have successfully run the analysis but I was wondering how I know what label corresponds to what sample? 

I have 12 samples and in the end, I got only labels S01 - S12. Looking for a positive response thanks in advance.

**Comment by dmnfarrell** [comment]
It should write out a samplefile.txt in the output folder that identifies the samples. This was done to avoid very large sample names in the columns but it's probably annoying for a lot of people. You can try to set add_labels = 0 in the config file to avoid this.

**Comment by Adnanhashim** [comment]
Perfect thanks although it is clearly mentioned in the configuration file setting and somehow I missed it.
